POST http://127.0.0.1:3000/auth/register
Content-Type: application/json

{
    "name":"prueba3",
    "email":"gabriel@live.com",
    "password":"123456"

}


### login sin conexion a BDD

POST  http://127.0.0.1:3000/auth/login
Content-Type: application/json

{
    "name":"prueba3",
    "email":"gabriel@live.com",
    "password":"123456"  

}

### users
GET http://127.0.0.1:3000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsImlkIjoxLCJpYXQiOjE3MzAyMTM5MDcsImV4cCI6MTczMDIxMzk2N30.AAMt-yffQXS5Sayh30vRwKP4UdHPfD_yEeBL3YwziFI